/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  mySidebar: [
    // 正常语法：
    {
      type: 'doc',
      id: 'intro', // 文档 ID
      label: '介绍', // 侧边栏标签
    },
    {
      type: 'category',
      label: '后端',
      items: [
          'Java基础',
          '单例模式',
          'Spring Boot',
          'Git常用命令',
          'GitHub搜索',
          'MySQL索引',
          'Redis基础',
          '正向代理和反向代理的区别',
          '自定义注解打印接口时长',
          '使用Hutool工具类自定义多sheet情况下去除默认的空sheet1',
          'Nginx部署AntDesignPro',
          'stream',
          'Maven集成CheckStyle',
          'XXL-JOB初探',
          'Springboot导出PDF文件',
          'URL下载文件工具类',
          '恢复docker容器数据',
          'byte',
          'SpringBoot应用接入Graylog',
          'Filter过滤器',
          'Logback日志增加链路追踪'
      ]
    },
    {
      type: 'category',
      label: '前端',
      items: [
          'Vue发送请求下载文件'
      ]
    },
    {
      type: 'category',
      label: '运维',
      items: [
          'Linux常用命令',
          '逻辑卷管理器-LVM',          
          'yum源配置',
          'Java安装与配置',
          'MySQL安装与配置',
          'Redis安装与配置',
          'Git安装与配置',
          'Maven安装与配置',
          'Nginx安装与配置',
          'Docker安装与配置',
          'Node.js安装与配置',
          'Zookeeper安装与配置',
          'Kafka安装与配置',
          'Elasticsearch安装与配置',
          'Logstash安装与导入数据',
          'Kibana的安装与界面快速浏览',
          'Jenkins安装与配置',
          'K8s部署Dashboard'
      ]
    },    
    {
      type: 'category',
      label: '杂文',
      items: [
          '虚拟机安装CentOS7',
          'Windows-MySQL安装与配置',
          'Windows-Gradle安装与配置',
          'Windows-Node.js安装与配置',
          '窗口移到屏幕边上拉不出来'
     ]
    }
  ]
};

module.exports = sidebars;
